### ISSUE TITLE
Define file data format for the LEI kite geometry

### ISSUE THREAD

**Issue by ufechner7** [OpenSourceAWE/VortexStepMethod.jl#133]
In Python, currently three csv files are used. These should be replaced by one yaml file.

**Comment by ufechner7** [comment]
In Python:
```
        wing_instance (Wing): Wing instance
        file_path (str): Path to the wing geometry file
            a .csv structured with columns: LE_x,LE_y,LE_z,TE_x,TE_y,TE_z,d_tube,camber
        is_with_corrected_polar (bool, optional): Whether to use corrected polar data. Defaults to False.
        path_polar_data_dir (str, optional): Path to the corrected polar data directory. Defaults to "".
            a .csv structured with columsn: alpha,cl,cd,cm
        is_with_bridles (bool, optional): Whether to include bridles. Defaults to False.
        path_bridle_data (str, optional): Path to the bridle data file. Defaults to None.
            a .csv structured with columsn: p1_x,p1_y,p1_z,p2_x,p2_y,p2_z,diameter
```

**Comment by 1-Bart-1** [comment]
Are the csv files in python generated with the surfplan adapter?

**Comment by ufechner7** [comment]
Jelle said there are lots of different ways to generate the CSV files, sometimes manually.

**Comment by 1-Bart-1** [comment]
Fine with me, go ahead!

**Comment by ufechner7** [comment]
First suggestion:
```yaml
vsm_model:
    name: "TU Delft LEI-kite V3"
    authors: "Jelle Poland et al"
    year: 2025
geometry:
    - [LE_x,LE_y,LE_z,TE_x,TE_y,TE_z,d_tube,camber]
    - [0.52218,4.1459378000000005,0.921215,0.86682,4.152601,0.932607,0.3225132246121334,0.0405837]
    - [0.263184,4.128047333333334,0.971623,0.874727,4.141856,0.979216,0.1837401335882308,0.043495]
    - [0.028112,4.110713133333333,1.049881,0.887481,4.124523,1.054402,0.131075032683328,0.0464063]
    - [-0.183243,4.09143955,1.154511,0.904737,4.101072,1.156125,0.1036781577453383,0.0493176]
    - [-0.368472,4.071198533333334,1.28343,0.926149,4.071974,1.282342,0.0872295732744705,0.0522289]
    - [-0.522929,4.044764516666667,1.43433,0.951369,4.0377,1.431014,0.0766805595131155,0.0551402]
    - [-0.639766,4.0122215,1.604842,0.980052,3.998721,1.600098,0.0698647554531404,0.0580515]
    - [-0.709238,3.97555605,1.791356,1.011852,3.955506,1.787553,0.0880585272944216,0.0580515]
    - [-0.79088,3.8134530499999997,2.209568,1.189372,3.789238,2.199439,0.0818347949026424,0.0656764]
    - [-0.864219,3.50976455,2.540205,1.256822,3.485499,2.522089,0.0805359612271219,0.0720449]
    - [-0.929298,3.1432477,2.796493,1.310901,3.116753,2.773988,0.0795641444833332,0.0774354]
    - [-0.986158,2.8075264499999997,3.092998,1.354755,2.780285,3.065722,0.0788201065048211,0.0819918]
    - [-1.034831,2.4026866,3.288677,1.390237,2.380855,3.254511,0.0782455219828932,0.0857993]
    - [-1.075348,1.969432,3.398648,1.41853,1.946587,3.361473,0.0778048283060423,0.0889127]
    - [-1.107733,1.5636341,3.587398,1.440421,1.540958,3.547442,0.0774738261221235,0.0913686]
    - [-1.132004,1.1212366,3.671702,1.456442,1.107796,3.627957,0.0772367956750012,0.0931918]
    - [-1.148177,0.6743327499999999,3.658834,1.466944,0.660721,3.613797,0.0770843584417728,0.0943989]
    - [-1.156262,0.23513389999999998,3.741837,1.472144,0.220752,3.696209,0.0769999920939645,0.095]
    - [-1.156262,-0.23513389999999998,3.741837,1.472144,-0.220752,3.696209,0.0769999920939645,0.095]
    - [-1.148177,-0.6743327499999999,3.658834,1.466944,-0.660721,3.613797,0.0770843584417728,0.0943989]
    - [-1.132004,-1.1212366,3.671702,1.456442,-1.107796,3.627957,0.0772367956750012,0.0931918]
    - [-1.107733,-1.5636341,3.587398,1.440421,-1.540958,3.547442,0.0774738261221235,0.0913686]
    - [-1.075348,-1.969432,3.398648,1.41853,-1.946587,3.361473,0.0778048283060423,0.0889127]
    - [-1.034831,-2.4026866,3.288677,1.390237,-2.380855,3.254511,0.0782455219828932,0.0857993]
    - [-0.986158,-2.8075264499999997,3.092998,1.354755,-2.780285,3.065722,0.0788201065048211,0.0819918]
    - [-0.929298,-3.1432477,2.796493,1.310901,-3.116753,2.773988,0.0795641444833332,0.0774354]
    - [-0.864219,-3.50976455,2.540205,1.256822,-3.485499,2.522089,0.0805359612271219,0.0720449]
    - [-0.79088,-3.8134530499999997,2.209568,1.189372,-3.789238,2.199439,0.0818347949026424,0.0656764]
    - [-0.709238,-3.97555605,1.791356,1.011852,-3.955506,1.787553,0.0880585272944216,0.0580515]
    - [-0.639766,-4.0122215,1.604842,0.980052,-3.998721,1.600098,0.0698647554531404,0.0580515]
    - [-0.522929,-4.044764516666667,1.43433,0.951369,-4.0377,1.431014,0.0766805595131155,0.0551402]
    - [-0.368472,-4.071198533333334,1.28343,0.926149,-4.071974,1.282342,0.0872295732744705,0.0522289]
    - [-0.183243,-4.09143955,1.154511,0.904737,-4.101072,1.156125,0.1036781577453383,0.0493176]
    - [0.028112,-4.110713133333333,1.049881,0.887481,-4.124523,1.054402,0.131075032683328,0.0464063]
    - [0.263184,-4.128047333333334,0.971623,0.874727,-4.141856,0.979216,0.1837401335882308,0.043495]
    - [0.52218,-4.1459378000000005,0.921215,0.86682,-4.152601,0.932607,0.3225132246121334,0.0405837]
polars:
    folder: "2D_polar_input"
    fields: "alpha,cl,cd,cm,cl_new,cd_new,cm_new,cl_breukels,cd_breukels,cm_breukels,cl_neuralfoil,cd_neuralfoil,cm_neuralfoil"
    active_fields: "alpha, cl_new, cd_new, cm"
    files: 
    - "corrected_polar_00.csv"
    - "corrected_polar_01.csv"
    - "corrected_polar_02.csv"
    - "corrected_polar_03.csv"
    - "corrected_polar_04.csv"
    - "corrected_polar_05.csv"
    - "corrected_polar_06.csv"
    - "corrected_polar_07.csv"
    - "corrected_polar_08.csv"
    - "corrected_polar_09.csv"
    - "corrected_polar_10.csv"
    - "corrected_polar_11.csv"
    - "corrected_polar_12.csv"
    - "corrected_polar_13.csv"
    - "corrected_polar_14.csv"
    - "corrected_polar_15.csv"
    - "corrected_polar_16.csv"
    - "corrected_polar_17.csv"
    - "corrected_polar_18.csv"
    - "corrected_polar_19.csv"
    - "corrected_polar_20.csv"
    - "corrected_polar_21.csv"
    - "corrected_polar_22.csv"
    - "corrected_polar_23.csv"
    - "corrected_polar_24.csv"
    - "corrected_polar_25.csv"
    - "corrected_polar_26.csv"
    - "corrected_polar_27.csv"
    - "corrected_polar_28.csv"
    - "corrected_polar_29.csv"
    - "corrected_polar_30.csv"
    - "corrected_polar_31.csv"
    - "corrected_polar_32.csv"
    - "corrected_polar_33.csv"
    - "corrected_polar_34.csv"
    - "corrected_polar_35.csv"
```
@jellepoland What is the difference between the 35 csv files?
